name: Pack new release

on:
  push:
    branches: [master, dev]

jobs:
  pack:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node Env
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Lint & Build
        run: |
          npm run lint
          npm run install
          npm run build-production

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-output
          path: dist
          retention-days: 3
