name: Pack new release

on:
  push:
    branches: [master, dev]

jobs:
  pack:
    name: Pack Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node Env
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Lint & Build
        run: |
          npm install
          npm run lint
          npm run build-production

      - name: ZIP Release
        run: |
          apt-get update && apt-get install -y zip
          cd dist/ && zip -r release.zip .

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-output
          path: dist/release.zip
          retention-days: 3
